application: gdn-short-code
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /admin/.*
  script: admin.app
  login: admin
  secure: always
- url: /api/.*
  script: api.app
  secure: always
- url: /.*
  script: app.app
  secure: always

libraries:
- name: jinja2
  version: latest